771 psalm config 7 1 x
chameleon-system/chameleon-shop pull request #121
Opened 2022-04-22 13:29 UTC by j6s

| Q             | A
| ------------- | ---
| Branch        | 7.1.x
| Bug fix?      | no
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed issues  | chameleon-system/chameleon-system#771   
| License       | MIT

Sister PR to https://github.com/chameleon-system/chameleon-shop/pull/120 - contains the same changes as https://github.com/chameleon-system/chameleon-shop/pull/120 but merged `7.1.x` into the branch and is opened against `7.1.x` in order to prevent merge conflicts.

The only changes between this and #120 are the following 2 commits:

* 9ddf54fab4e7ad8f412424652c281067fc54353b (merge commit)
* 980d47233099ddef166d850f8614fd01515b9dae

2022-06-09 13:11 UTC, bestform requested changes

2022-07-01 10:35 UTC, j6s commented on src/SearchBundle/objects/db/TShopSearchCache.class.php
> +     * @param string $sLanguageId
:heavy_check_mark:

2022-07-01 10:38 UTC, j6s commented on src/SearchBundle/objects/db/TShopSearchLog.class.php
> +     * @param string $sLanguageId
:heavy_check_mark:

2022-07-01 10:39 UTC, j6s commented on src/ShopAffiliateBundle/objects/db/TPkgShopAffiliateList.class.php
> +     * @param string $sLanguageId
:heavy_check_mark:

2022-07-01 10:39 UTC, j6s commented on src/ShopArticleDetailPagingBundle/Service/AddParametersToUrlService.php
> +     * @param null|string $url
:heavy_check_mark:

2022-07-01 10:42 UTC, j6s commented on src/ShopBundle/Service/ShopSearchSuggest.php
> +        /** @var array{name:string}[] $results */
First off: It should actually be `array{name: string, articlenumber: string}`

We are selecting `name` and `articlenumber` from the database. The return value of `fetchAll` will be a sequential array of associative arrays that each contain `name` and `articlenumber` keys - e.g.

```php
[
    [ 'name' => 'foo', 'articlenumber' => 'bar' ],
    [ 'name' => 'foo', 'articlenumber' => 'bar' ],
    [ 'name' => 'foo', 'articlenumber' => 'bar' ],
]
```

Maybe the following would be more immediately recognizable?

```
list<array{name: string, articlenumber: string}>
```

2022-07-01 10:43 UTC, j6s commented on src/ShopBundle/mappers/manufacturer/TPkgShopManufacturerMapper_Overview.class.php
> +     * @param bool|false $bCachingEnabled
:heavy_check_mark:

2022-07-01 10:44 UTC, j6s commented on src/ShopBundle/mappers/order/TPkgShopMapper_OrderArticleList.class.php
> +     * @param bool|false $bCachingEnabled
:heavy_check_mark:  I swear I wasn't drinking

2022-07-01 10:44 UTC, j6s commented on src/ShopBundle/mappers/order/TPkgShopMapper_OrderPayment.class.php
> +     * @param bool|false $bCachingEnabled
:heavy_check_mark:

2022-07-01 10:45 UTC, j6s commented on src/ShopBundle/objects/BackendModules/MTShopStatistic/MTShopStatistic.class.php
> +     * - (int) 0 If the column does not exist and has no subGroups - irresponsible of the value of `bShowGrandTotal`
:heavy_check_mark:  Yes, that's what I meant

2022-07-01 10:46 UTC, j6s commented on src/ShopBundle/objects/WebModules/MTShopBasketCore/MTShopBasketCoreEndpoint.class.php
> +     * @return void
:heavy_check_mark: I added them (I didn't add `bool|false` though)

2022-07-01 10:47 UTC, j6s commented on src/ShopBundle/objects/WebModules/MTShopOrderWizardCore/MTShopOrderWizardCoreEndPoint.class.php
> +     * @return false|null
:heavy_check_mark:

2022-07-01 10:49 UTC, j6s commented on src/ShopBundle/objects/db/TShopOrderStep/TShopOrderStepList.class.php
> +     * @param string $sSpotName
:heavy_check_mark:

2022-07-01 10:50 UTC, j6s commented on src/ShopListFilterBundle/objects/db/TPkgShopListfilterItemList.class.php
> +     * @param string|null $iLanguageId
:heavy_check_mark:

2022-07-26 07:33 UTC, merged