7.2/59090 symfony security
chameleon-system/chameleon-shop pull request #136
Opened 2023-01-02 10:31 UTC by rnuernberg

2023-01-13 12:14 UTC, bestform requested changes

2023-01-13 12:14 UTC, bestform commented on src/ShopBundle/objects/db/TShopPaymentHandler/TShopPaymentHandlerPayPalExpress.class.php
> +    protected function GetUserDataFromPayPalData($aBilling, $aShipping)
This needs to stay

2023-01-13 12:14 UTC, bestform commented on src/ShopBundle/objects/db/TShopVariantDisplayHandler/TShopVariantDisplayHandler.class.php
> +    protected function AddClearCacheTriggers($aClearTriggers, $oArticle, $sViewName, $sViewType)
This needs to stay

2023-01-13 12:14 UTC, bestform commented on src/ShopListFilterBundle/objects/db/ListfilterItems/TPkgShopListfilterItemVariant.class.php
> +    protected function OrderOptions($aOptions)
This needs stay

2023-01-13 12:14 UTC, bestform commented on src/ShopListFilterBundle/objects/db/ListfilterItems/TPkgShopListfilterItemVariantColor.class.php
> +    protected function OrderOptions($aOptions)
please stay another day

2023-01-13 12:14 UTC, bestform commented on src/ShopListFilterBundle/objects/db/TPkgShopListfilterItem.class.php
> +    protected function OrderOptions($aOptions)
Stay

2023-01-16 08:54 UTC, rnuernberg commented on src/ImageHotspotBundle/objects/db/TPkgImageHotspotItem.class.php
> +    protected function AddClearCacheTriggers($aClearTriggers, $sViewName, $sViewType)
item caching is no longer used - method removed

2023-01-16 08:55 UTC, rnuernberg commented on src/ShopBundle/objects/ArticleList/Module.php
> +    private function makePageSizeValid(array $stateData)
private method - changed to return data

2023-01-16 09:05 UTC, rnuernberg commented on src/ShopBundle/objects/TShopBasket/TShopBasketArticleCoreList.class.php
> +    public function next(): TShopBasketArticle|false
sad. changed... also affects the auto classes generated by the core - and any usages of the classes

2023-01-16 09:07 UTC, rnuernberg commented on src/ShopBundle/objects/TShopBasket/TShopBasketArticleDiscountCoreList.class.php
> +    public function next(): TdbShopDiscount|false
done

2023-01-16 09:07 UTC, rnuernberg commented on src/ShopBundle/objects/TShopBasket/TShopBasketArticleDiscountCoreList.class.php
> +    public function current():TdbShopDiscount|false
done

2023-01-16 09:07 UTC, rnuernberg commented on src/ShopBundle/objects/TShopBasket/TShopBasketDiscountCoreList.class.php
> +    public function next(): TdbShopDiscount|false
done

2023-01-16 09:07 UTC, rnuernberg commented on src/ShopBundle/objects/TShopBasket/TShopBasketVoucherCoreList.class.php
> +    public function next(): TdbShopVoucher|false
done

2023-01-16 09:09 UTC, rnuernberg commented on src/ShopBundle/objects/db/TShopArticle.class.php
> +    public function GetSeoPattern($sPaternIn)
true

2023-01-16 09:12 UTC, rnuernberg commented on src/ShopBundle/objects/db/TShopPaymentHandler/TShopPaymentHandlerPayPalExpress.class.php
> +    protected function GetUserDataFromPayPalData($aBilling, $aShipping)
reverted

2023-01-16 09:13 UTC, rnuernberg commented on src/ShopBundle/objects/db/TShopVariantDisplayHandler/TShopVariantDisplayHandler.class.php
> +    protected function AddClearCacheTriggers($aClearTriggers, $oArticle, $sViewName, $sViewType)
method is no longer needed - removed

2023-01-16 09:14 UTC, rnuernberg commented on src/ShopListFilterBundle/objects/db/ListfilterItems/TPkgShopListfilterItemVariant.class.php
> +    protected function OrderOptions($aOptions)
reverted

2023-01-16 09:14 UTC, rnuernberg commented on src/ShopListFilterBundle/objects/db/ListfilterItems/TPkgShopListfilterItemVariantColor.class.php
> +    protected function OrderOptions($aOptions)
reverted

2023-01-16 09:15 UTC, rnuernberg commented on src/ShopListFilterBundle/objects/db/TPkgShopListfilterItem.class.php
> +    protected function OrderOptions($aOptions)
reverted

2023-01-16 13:26 UTC, bestform commented
I resolved the conflicts to the best of my knowledge. Could you please have a quick look at my commit to confirm that I didn't do anything stupid?

2023-01-16 15:20 UTC, rnuernberg commented
> I resolved the conflicts to the best of my knowledge. Could you please have a quick look at my commit to confirm that I didn't do anything stupid?

I have no idea where to find your commit.

2023-01-17 13:37 UTC, rnuernberg commented
> It is the last merge commit: [5978322](https://github.com/chameleon-system/chameleon-shop/commit/59783222cedac62e6f294e447df40b4a7fdffe11)

looks good

2023-01-19 09:43 UTC, merged