Add basketUrl post render variable
chameleon-system/chameleon-shop pull request #92
Opened 2020-11-05 15:33 UTC by j6s

Together with the template change in chameleon-shop-theme-bundle, this
fixes #654

| Q             | A
| ------------- | ---
| Branch        | 6.3.x
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no     
| Deprecations? | no 
| Fixed issues  | chameleon-system/chameleon-system#654
| License       | MIT

This PR adds the `basketUrl` post render variable for usage in the mini shop basket templates in order to
prevent caching of the 'continue shopping' URL.

2020-11-05 15:47 UTC, bestform requested changes

2020-11-05 15:47 UTC, bestform commented on src/ShopBundle/objects/WebModules/MTShopBasketCore/MTShopBasketCoreEndpoint.class.php
> +        return $variables;
Nothing big, but the symfony conding standard want to have a blank line before a return.

Quote:
`Add a blank line before return statements, unless the return is alone inside a statement-group (like an if statement);`

2020-11-06 12:28 UTC, UlrichKu commented on src/ShopBundle/Bridge/Chameleon/Migration/Script/update-1604649540.inc.php
> +TCMSLogChange::addInfoMessage('If you are using a custom theme you need replace the {{sBasketUrl}} template variable with the [{basketUrl}] post render variable in the shopBasketMiniBasket and shopBa
Should be warning.

2020-11-06 12:28 UTC, UlrichKu commented on src/ShopBundle/Bridge/Chameleon/Migration/Script/update-1604649540.inc.php
> +    - Add Post render variable for basket URL to prevent accidental caching of it
ref #654: Show warning message about changing basket url    (or similar)

2020-11-12 14:31 UTC, merged